### ISSUE TITLE
Add unit testing

### ISSUE THREAD

**Issue by mfansler** [conda-forge/pymde-feedstock#2]
Would it make sense to run the unit tests in the recipe? Something like

```
test:
  requires:
    - pytest
  source_files:
    - pymde/
  imports:
    - pymde
  commands:
    - pytest pymde/ -v
 ```

_Originally posted by @akshayka in https://github.com/conda-forge/staged-recipes/issues/14383#issuecomment-806861970_
